/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.ceffective.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.ceffective.ui.internal.CeffectiveActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CeffectiveExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(CeffectiveActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		CeffectiveActivator activator = CeffectiveActivator.getInstance();
		return activator != null ? activator.getInjector(CeffectiveActivator.ORG_XTEXT_EXAMPLE_CEFFECTIVE_CEFFECTIVE) : null;
	}

}
