/**
 *
 * $Id$
 */
package Ceffective.validation;

import Ceffective.AmbienteDespliegue;
import Ceffective.AutenticacionUsuario;
import Ceffective.VPC;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Ceffective.ProveedorNube}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProveedorNubeValidator {
	boolean validate();

	boolean validateNombre(String value);
	boolean validateAmbientedespliegue(EList<AmbienteDespliegue> value);
	boolean validateAutenticacionUsuario(EList<AutenticacionUsuario> value);
	boolean validateVpc(EList<VPC> value);
}
