/**
 *
 * $Id$
 */
package Ceffective.validation;

import Ceffective.Recurso;
import Ceffective.VPC;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Ceffective.Recurso}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RecursoValidator {
	boolean validate();

	boolean validateNombre(String value);
	boolean validateRecursos(EList<Recurso> value);
	boolean validateVpc(VPC value);
	boolean validateZonaDisponibilidad(String value);
	boolean validateZonaNombre(String value);
}
