/**
 *
 * $Id$
 */
package Ceffective.validation;


/**
 * A sample validator interface for {@link Ceffective.Regla}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ReglaValidator {
	boolean validate();

	boolean validateTipo(String value);
	boolean validateProtocolo(String value);
	boolean validatePuerto(String value);
	boolean validateOrigen(String value);
	boolean validateDescripcion(String value);
}
