/**
 *
 * $Id$
 */
package ceffective.validation;

import ceffective.MecanismoSeguridad;
import ceffective.Recurso;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ceffective.VPC}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VPCValidator {
	boolean validate();

	boolean validateNombre(String value);
	boolean validateMecanismoseguridad(EList<MecanismoSeguridad> value);
	boolean validateRecurso(EList<Recurso> value);
}
