/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.ceffective;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CeffectiveStandaloneSetup extends CeffectiveStandaloneSetupGenerated {

	public static void doSetup() {
		new CeffectiveStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
