/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.ceffective.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.ceffective.ui.internal.CeffectiveActivator;

public class CeffectiveUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CeffectiveActivator.getInstance().getInjector("org.xtext.example.ceffective.Ceffective");
	}

}
