/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.ceffective.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CeffectiveUiModule extends AbstractCeffectiveUiModule {

	public CeffectiveUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
