/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.ceffective.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.ceffective.ide.contentassist.antlr.internal.InternalCeffectiveParser;
import org.xtext.example.ceffective.services.CeffectiveGrammarAccess;

public class CeffectiveParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(CeffectiveGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, CeffectiveGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getAutenticacionUsuarioAccess().getAlternatives(), "rule__AutenticacionUsuario__Alternatives");
			builder.put(grammarAccess.getRecursoAccess().getAlternatives(), "rule__Recurso__Alternatives");
			builder.put(grammarAccess.getMecanismoSeguridadAccess().getAlternatives(), "rule__MecanismoSeguridad__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getTipoAmbienteAccess().getAlternatives(), "rule__TipoAmbiente__Alternatives");
			builder.put(grammarAccess.getTamanoServidorAccess().getAlternatives(), "rule__TamanoServidor__Alternatives");
			builder.put(grammarAccess.getTipoBaseDatosAccess().getAlternatives(), "rule__TipoBaseDatos__Alternatives");
			builder.put(grammarAccess.getCeffectiveAccess().getGroup(), "rule__Ceffective__Group__0");
			builder.put(grammarAccess.getCeffectiveAccess().getGroup_3(), "rule__Ceffective__Group_3__0");
			builder.put(grammarAccess.getProveedorNubeAccess().getGroup(), "rule__ProveedorNube__Group__0");
			builder.put(grammarAccess.getProveedorNubeAccess().getGroup_2(), "rule__ProveedorNube__Group_2__0");
			builder.put(grammarAccess.getProveedorNubeAccess().getGroup_3(), "rule__ProveedorNube__Group_3__0");
			builder.put(grammarAccess.getProveedorNubeAccess().getGroup_3_3(), "rule__ProveedorNube__Group_3_3__0");
			builder.put(grammarAccess.getProveedorNubeAccess().getGroup_4(), "rule__ProveedorNube__Group_4__0");
			builder.put(grammarAccess.getProveedorNubeAccess().getGroup_4_3(), "rule__ProveedorNube__Group_4_3__0");
			builder.put(grammarAccess.getProveedorNubeAccess().getGroup_8(), "rule__ProveedorNube__Group_8__0");
			builder.put(grammarAccess.getAmbienteDespliegueAccess().getGroup(), "rule__AmbienteDespliegue__Group__0");
			builder.put(grammarAccess.getAmbienteDespliegueAccess().getGroup_3(), "rule__AmbienteDespliegue__Group_3__0");
			builder.put(grammarAccess.getAmbienteDespliegueAccess().getGroup_4(), "rule__AmbienteDespliegue__Group_4__0");
			builder.put(grammarAccess.getAmbienteDespliegueAccess().getGroup_4_3(), "rule__AmbienteDespliegue__Group_4_3__0");
			builder.put(grammarAccess.getAutenticacionUsuario_ImplAccess().getGroup(), "rule__AutenticacionUsuario_Impl__Group__0");
			builder.put(grammarAccess.getAutenticacionUsuario_ImplAccess().getGroup_3(), "rule__AutenticacionUsuario_Impl__Group_3__0");
			builder.put(grammarAccess.getAutenticacionUsuario_ImplAccess().getGroup_4(), "rule__AutenticacionUsuario_Impl__Group_4__0");
			builder.put(grammarAccess.getVPCAccess().getGroup(), "rule__VPC__Group__0");
			builder.put(grammarAccess.getVPCAccess().getGroup_3(), "rule__VPC__Group_3__0");
			builder.put(grammarAccess.getVPCAccess().getGroup_4(), "rule__VPC__Group_4__0");
			builder.put(grammarAccess.getVPCAccess().getGroup_4_3(), "rule__VPC__Group_4_3__0");
			builder.put(grammarAccess.getVPCAccess().getGroup_5(), "rule__VPC__Group_5__0");
			builder.put(grammarAccess.getVPCAccess().getGroup_5_3(), "rule__VPC__Group_5_3__0");
			builder.put(grammarAccess.getServidorAplicacionesAccess().getGroup(), "rule__ServidorAplicaciones__Group__0");
			builder.put(grammarAccess.getServidorAplicacionesAccess().getGroup_3(), "rule__ServidorAplicaciones__Group_3__0");
			builder.put(grammarAccess.getServidorAplicacionesAccess().getGroup_4(), "rule__ServidorAplicaciones__Group_4__0");
			builder.put(grammarAccess.getServidorAplicacionesAccess().getGroup_5(), "rule__ServidorAplicaciones__Group_5__0");
			builder.put(grammarAccess.getServidorAplicacionesAccess().getGroup_6(), "rule__ServidorAplicaciones__Group_6__0");
			builder.put(grammarAccess.getServidorAplicacionesAccess().getGroup_7(), "rule__ServidorAplicaciones__Group_7__0");
			builder.put(grammarAccess.getServidorAplicacionesAccess().getGroup_8(), "rule__ServidorAplicaciones__Group_8__0");
			builder.put(grammarAccess.getServidorAplicacionesAccess().getGroup_8_3(), "rule__ServidorAplicaciones__Group_8_3__0");
			builder.put(grammarAccess.getServidorAplicacionesAccess().getGroup_9(), "rule__ServidorAplicaciones__Group_9__0");
			builder.put(grammarAccess.getAlmacenamientoAccess().getGroup(), "rule__Almacenamiento__Group__0");
			builder.put(grammarAccess.getAlmacenamientoAccess().getGroup_3(), "rule__Almacenamiento__Group_3__0");
			builder.put(grammarAccess.getAlmacenamientoAccess().getGroup_4(), "rule__Almacenamiento__Group_4__0");
			builder.put(grammarAccess.getAlmacenamientoAccess().getGroup_5(), "rule__Almacenamiento__Group_5__0");
			builder.put(grammarAccess.getAlmacenamientoAccess().getGroup_6(), "rule__Almacenamiento__Group_6__0");
			builder.put(grammarAccess.getAlmacenamientoAccess().getGroup_7(), "rule__Almacenamiento__Group_7__0");
			builder.put(grammarAccess.getAlmacenamientoAccess().getGroup_7_3(), "rule__Almacenamiento__Group_7_3__0");
			builder.put(grammarAccess.getAlmacenamientoAccess().getGroup_8(), "rule__Almacenamiento__Group_8__0");
			builder.put(grammarAccess.getServidorBDAccess().getGroup(), "rule__ServidorBD__Group__0");
			builder.put(grammarAccess.getServidorBDAccess().getGroup_3(), "rule__ServidorBD__Group_3__0");
			builder.put(grammarAccess.getServidorBDAccess().getGroup_4(), "rule__ServidorBD__Group_4__0");
			builder.put(grammarAccess.getServidorBDAccess().getGroup_5(), "rule__ServidorBD__Group_5__0");
			builder.put(grammarAccess.getServidorBDAccess().getGroup_6(), "rule__ServidorBD__Group_6__0");
			builder.put(grammarAccess.getServidorBDAccess().getGroup_7(), "rule__ServidorBD__Group_7__0");
			builder.put(grammarAccess.getServidorBDAccess().getGroup_8(), "rule__ServidorBD__Group_8__0");
			builder.put(grammarAccess.getServidorBDAccess().getGroup_9(), "rule__ServidorBD__Group_9__0");
			builder.put(grammarAccess.getServidorBDAccess().getGroup_9_3(), "rule__ServidorBD__Group_9_3__0");
			builder.put(grammarAccess.getServidorBDAccess().getGroup_10(), "rule__ServidorBD__Group_10__0");
			builder.put(grammarAccess.getServidor_ImplAccess().getGroup(), "rule__Servidor_Impl__Group__0");
			builder.put(grammarAccess.getServidor_ImplAccess().getGroup_3(), "rule__Servidor_Impl__Group_3__0");
			builder.put(grammarAccess.getServidor_ImplAccess().getGroup_4(), "rule__Servidor_Impl__Group_4__0");
			builder.put(grammarAccess.getServidor_ImplAccess().getGroup_5(), "rule__Servidor_Impl__Group_5__0");
			builder.put(grammarAccess.getServidor_ImplAccess().getGroup_6(), "rule__Servidor_Impl__Group_6__0");
			builder.put(grammarAccess.getServidor_ImplAccess().getGroup_7(), "rule__Servidor_Impl__Group_7__0");
			builder.put(grammarAccess.getServidor_ImplAccess().getGroup_7_3(), "rule__Servidor_Impl__Group_7_3__0");
			builder.put(grammarAccess.getServidor_ImplAccess().getGroup_8(), "rule__Servidor_Impl__Group_8__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getAutenticacionBasicaAccess().getGroup(), "rule__AutenticacionBasica__Group__0");
			builder.put(grammarAccess.getAutenticacionBasicaAccess().getGroup_3(), "rule__AutenticacionBasica__Group_3__0");
			builder.put(grammarAccess.getAutenticacionBasicaAccess().getGroup_4(), "rule__AutenticacionBasica__Group_4__0");
			builder.put(grammarAccess.getAutenticacionBasicaAccess().getGroup_5(), "rule__AutenticacionBasica__Group_5__0");
			builder.put(grammarAccess.getAutenticacionFirmaAccess().getGroup(), "rule__AutenticacionFirma__Group__0");
			builder.put(grammarAccess.getAutenticacionFirmaAccess().getGroup_3(), "rule__AutenticacionFirma__Group_3__0");
			builder.put(grammarAccess.getAutenticacionFirmaAccess().getGroup_4(), "rule__AutenticacionFirma__Group_4__0");
			builder.put(grammarAccess.getAutenticacionFirmaAccess().getGroup_5(), "rule__AutenticacionFirma__Group_5__0");
			builder.put(grammarAccess.getAutenticacionFirmaAccess().getGroup_6(), "rule__AutenticacionFirma__Group_6__0");
			builder.put(grammarAccess.getSubredAccess().getGroup(), "rule__Subred__Group__0");
			builder.put(grammarAccess.getSubredAccess().getGroup_3(), "rule__Subred__Group_3__0");
			builder.put(grammarAccess.getSubredAccess().getGroup_4(), "rule__Subred__Group_4__0");
			builder.put(grammarAccess.getSubredAccess().getGroup_5(), "rule__Subred__Group_5__0");
			builder.put(grammarAccess.getSubredAccess().getGroup_6(), "rule__Subred__Group_6__0");
			builder.put(grammarAccess.getInternetGatewayAccess().getGroup(), "rule__InternetGateway__Group__0");
			builder.put(grammarAccess.getInternetGatewayAccess().getGroup_3(), "rule__InternetGateway__Group_3__0");
			builder.put(grammarAccess.getInternetGatewayAccess().getGroup_4(), "rule__InternetGateway__Group_4__0");
			builder.put(grammarAccess.getInternetGatewayAccess().getGroup_5(), "rule__InternetGateway__Group_5__0");
			builder.put(grammarAccess.getGrupoSeguridadAccess().getGroup(), "rule__GrupoSeguridad__Group__0");
			builder.put(grammarAccess.getGrupoSeguridadAccess().getGroup_2(), "rule__GrupoSeguridad__Group_2__0");
			builder.put(grammarAccess.getGrupoSeguridadAccess().getGroup_3(), "rule__GrupoSeguridad__Group_3__0");
			builder.put(grammarAccess.getGrupoSeguridadAccess().getGroup_4(), "rule__GrupoSeguridad__Group_4__0");
			builder.put(grammarAccess.getGrupoSeguridadAccess().getGroup_5(), "rule__GrupoSeguridad__Group_5__0");
			builder.put(grammarAccess.getGrupoSeguridadAccess().getGroup_9(), "rule__GrupoSeguridad__Group_9__0");
			builder.put(grammarAccess.getGrupoSeguridadAccess().getGroup_14(), "rule__GrupoSeguridad__Group_14__0");
			builder.put(grammarAccess.getReglaAccess().getGroup(), "rule__Regla__Group__0");
			builder.put(grammarAccess.getReglaAccess().getGroup_3(), "rule__Regla__Group_3__0");
			builder.put(grammarAccess.getReglaAccess().getGroup_4(), "rule__Regla__Group_4__0");
			builder.put(grammarAccess.getReglaAccess().getGroup_5(), "rule__Regla__Group_5__0");
			builder.put(grammarAccess.getReglaAccess().getGroup_6(), "rule__Regla__Group_6__0");
			builder.put(grammarAccess.getReglaAccess().getGroup_7(), "rule__Regla__Group_7__0");
			builder.put(grammarAccess.getCeffectiveAccess().getProveedorNubeAssignment_3_1(), "rule__Ceffective__ProveedorNubeAssignment_3_1");
			builder.put(grammarAccess.getProveedorNubeAccess().getNombreAssignment_2_1(), "rule__ProveedorNube__NombreAssignment_2_1");
			builder.put(grammarAccess.getProveedorNubeAccess().getAmbientedespliegueAssignment_3_2(), "rule__ProveedorNube__AmbientedespliegueAssignment_3_2");
			builder.put(grammarAccess.getProveedorNubeAccess().getAmbientedespliegueAssignment_3_3_1(), "rule__ProveedorNube__AmbientedespliegueAssignment_3_3_1");
			builder.put(grammarAccess.getProveedorNubeAccess().getVpcAssignment_4_2(), "rule__ProveedorNube__VpcAssignment_4_2");
			builder.put(grammarAccess.getProveedorNubeAccess().getVpcAssignment_4_3_1(), "rule__ProveedorNube__VpcAssignment_4_3_1");
			builder.put(grammarAccess.getProveedorNubeAccess().getAutenticacionUsuarioAssignment_7(), "rule__ProveedorNube__AutenticacionUsuarioAssignment_7");
			builder.put(grammarAccess.getProveedorNubeAccess().getAutenticacionUsuarioAssignment_8_1(), "rule__ProveedorNube__AutenticacionUsuarioAssignment_8_1");
			builder.put(grammarAccess.getAmbienteDespliegueAccess().getAmbienteAssignment_3_1(), "rule__AmbienteDespliegue__AmbienteAssignment_3_1");
			builder.put(grammarAccess.getAmbienteDespliegueAccess().getRecursosAssignment_4_2(), "rule__AmbienteDespliegue__RecursosAssignment_4_2");
			builder.put(grammarAccess.getAmbienteDespliegueAccess().getRecursosAssignment_4_3_1(), "rule__AmbienteDespliegue__RecursosAssignment_4_3_1");
			builder.put(grammarAccess.getAutenticacionUsuario_ImplAccess().getUsuarioAssignment_3_1(), "rule__AutenticacionUsuario_Impl__UsuarioAssignment_3_1");
			builder.put(grammarAccess.getAutenticacionUsuario_ImplAccess().getCorreoAssignment_4_1(), "rule__AutenticacionUsuario_Impl__CorreoAssignment_4_1");
			builder.put(grammarAccess.getVPCAccess().getNombreAssignment_3_1(), "rule__VPC__NombreAssignment_3_1");
			builder.put(grammarAccess.getVPCAccess().getMecanismoseguridadAssignment_4_2(), "rule__VPC__MecanismoseguridadAssignment_4_2");
			builder.put(grammarAccess.getVPCAccess().getMecanismoseguridadAssignment_4_3_1(), "rule__VPC__MecanismoseguridadAssignment_4_3_1");
			builder.put(grammarAccess.getVPCAccess().getRecursoAssignment_5_2(), "rule__VPC__RecursoAssignment_5_2");
			builder.put(grammarAccess.getVPCAccess().getRecursoAssignment_5_3_1(), "rule__VPC__RecursoAssignment_5_3_1");
			builder.put(grammarAccess.getServidorAplicacionesAccess().getNombreAssignment_3_1(), "rule__ServidorAplicaciones__NombreAssignment_3_1");
			builder.put(grammarAccess.getServidorAplicacionesAccess().getZonaDisponibilidadAssignment_4_1(), "rule__ServidorAplicaciones__ZonaDisponibilidadAssignment_4_1");
			builder.put(grammarAccess.getServidorAplicacionesAccess().getZonaNombreAssignment_5_1(), "rule__ServidorAplicaciones__ZonaNombreAssignment_5_1");
			builder.put(grammarAccess.getServidorAplicacionesAccess().getTamanoAssignment_6_1(), "rule__ServidorAplicaciones__TamanoAssignment_6_1");
			builder.put(grammarAccess.getServidorAplicacionesAccess().getSistemaOperativoAssignment_7_1(), "rule__ServidorAplicaciones__SistemaOperativoAssignment_7_1");
			builder.put(grammarAccess.getServidorAplicacionesAccess().getRecursosAssignment_8_2(), "rule__ServidorAplicaciones__RecursosAssignment_8_2");
			builder.put(grammarAccess.getServidorAplicacionesAccess().getRecursosAssignment_8_3_1(), "rule__ServidorAplicaciones__RecursosAssignment_8_3_1");
			builder.put(grammarAccess.getServidorAplicacionesAccess().getVpcAssignment_9_1(), "rule__ServidorAplicaciones__VpcAssignment_9_1");
			builder.put(grammarAccess.getAlmacenamientoAccess().getNombreAssignment_3_1(), "rule__Almacenamiento__NombreAssignment_3_1");
			builder.put(grammarAccess.getAlmacenamientoAccess().getZonaDisponibilidadAssignment_4_1(), "rule__Almacenamiento__ZonaDisponibilidadAssignment_4_1");
			builder.put(grammarAccess.getAlmacenamientoAccess().getZonaNombreAssignment_5_1(), "rule__Almacenamiento__ZonaNombreAssignment_5_1");
			builder.put(grammarAccess.getAlmacenamientoAccess().getTamanoInicialAssignment_6_1(), "rule__Almacenamiento__TamanoInicialAssignment_6_1");
			builder.put(grammarAccess.getAlmacenamientoAccess().getRecursosAssignment_7_2(), "rule__Almacenamiento__RecursosAssignment_7_2");
			builder.put(grammarAccess.getAlmacenamientoAccess().getRecursosAssignment_7_3_1(), "rule__Almacenamiento__RecursosAssignment_7_3_1");
			builder.put(grammarAccess.getAlmacenamientoAccess().getVpcAssignment_8_1(), "rule__Almacenamiento__VpcAssignment_8_1");
			builder.put(grammarAccess.getServidorBDAccess().getNombreAssignment_3_1(), "rule__ServidorBD__NombreAssignment_3_1");
			builder.put(grammarAccess.getServidorBDAccess().getZonaDisponibilidadAssignment_4_1(), "rule__ServidorBD__ZonaDisponibilidadAssignment_4_1");
			builder.put(grammarAccess.getServidorBDAccess().getZonaNombreAssignment_5_1(), "rule__ServidorBD__ZonaNombreAssignment_5_1");
			builder.put(grammarAccess.getServidorBDAccess().getTamanoAssignment_6_1(), "rule__ServidorBD__TamanoAssignment_6_1");
			builder.put(grammarAccess.getServidorBDAccess().getTipoAssignment_7_1(), "rule__ServidorBD__TipoAssignment_7_1");
			builder.put(grammarAccess.getServidorBDAccess().getSistemaManejadorAssignment_8_1(), "rule__ServidorBD__SistemaManejadorAssignment_8_1");
			builder.put(grammarAccess.getServidorBDAccess().getRecursosAssignment_9_2(), "rule__ServidorBD__RecursosAssignment_9_2");
			builder.put(grammarAccess.getServidorBDAccess().getRecursosAssignment_9_3_1(), "rule__ServidorBD__RecursosAssignment_9_3_1");
			builder.put(grammarAccess.getServidorBDAccess().getVpcAssignment_10_1(), "rule__ServidorBD__VpcAssignment_10_1");
			builder.put(grammarAccess.getServidor_ImplAccess().getNombreAssignment_3_1(), "rule__Servidor_Impl__NombreAssignment_3_1");
			builder.put(grammarAccess.getServidor_ImplAccess().getZonaDisponibilidadAssignment_4_1(), "rule__Servidor_Impl__ZonaDisponibilidadAssignment_4_1");
			builder.put(grammarAccess.getServidor_ImplAccess().getZonaNombreAssignment_5_1(), "rule__Servidor_Impl__ZonaNombreAssignment_5_1");
			builder.put(grammarAccess.getServidor_ImplAccess().getTamanoAssignment_6_1(), "rule__Servidor_Impl__TamanoAssignment_6_1");
			builder.put(grammarAccess.getServidor_ImplAccess().getRecursosAssignment_7_2(), "rule__Servidor_Impl__RecursosAssignment_7_2");
			builder.put(grammarAccess.getServidor_ImplAccess().getRecursosAssignment_7_3_1(), "rule__Servidor_Impl__RecursosAssignment_7_3_1");
			builder.put(grammarAccess.getServidor_ImplAccess().getVpcAssignment_8_1(), "rule__Servidor_Impl__VpcAssignment_8_1");
			builder.put(grammarAccess.getAutenticacionBasicaAccess().getUsuarioAssignment_3_1(), "rule__AutenticacionBasica__UsuarioAssignment_3_1");
			builder.put(grammarAccess.getAutenticacionBasicaAccess().getCorreoAssignment_4_1(), "rule__AutenticacionBasica__CorreoAssignment_4_1");
			builder.put(grammarAccess.getAutenticacionBasicaAccess().getPasswordAssignment_5_1(), "rule__AutenticacionBasica__PasswordAssignment_5_1");
			builder.put(grammarAccess.getAutenticacionFirmaAccess().getUsuarioAssignment_3_1(), "rule__AutenticacionFirma__UsuarioAssignment_3_1");
			builder.put(grammarAccess.getAutenticacionFirmaAccess().getCorreoAssignment_4_1(), "rule__AutenticacionFirma__CorreoAssignment_4_1");
			builder.put(grammarAccess.getAutenticacionFirmaAccess().getNombreAssignment_5_1(), "rule__AutenticacionFirma__NombreAssignment_5_1");
			builder.put(grammarAccess.getAutenticacionFirmaAccess().getCertificadoAssignment_6_1(), "rule__AutenticacionFirma__CertificadoAssignment_6_1");
			builder.put(grammarAccess.getSubredAccess().getNombreAssignment_3_1(), "rule__Subred__NombreAssignment_3_1");
			builder.put(grammarAccess.getSubredAccess().getZonaNombreAssignment_4_1(), "rule__Subred__ZonaNombreAssignment_4_1");
			builder.put(grammarAccess.getSubredAccess().getZonaDisponibilidadAssignment_5_1(), "rule__Subred__ZonaDisponibilidadAssignment_5_1");
			builder.put(grammarAccess.getSubredAccess().getCidrBlockAssignment_6_1(), "rule__Subred__CidrBlockAssignment_6_1");
			builder.put(grammarAccess.getInternetGatewayAccess().getNombreAssignment_3_1(), "rule__InternetGateway__NombreAssignment_3_1");
			builder.put(grammarAccess.getInternetGatewayAccess().getZonaNombreAssignment_4_1(), "rule__InternetGateway__ZonaNombreAssignment_4_1");
			builder.put(grammarAccess.getInternetGatewayAccess().getZonaDisponibilidadAssignment_5_1(), "rule__InternetGateway__ZonaDisponibilidadAssignment_5_1");
			builder.put(grammarAccess.getGrupoSeguridadAccess().getNombreAssignment_2_1(), "rule__GrupoSeguridad__NombreAssignment_2_1");
			builder.put(grammarAccess.getGrupoSeguridadAccess().getZonaNombreAssignment_3_1(), "rule__GrupoSeguridad__ZonaNombreAssignment_3_1");
			builder.put(grammarAccess.getGrupoSeguridadAccess().getZonaDisponibilidadAssignment_4_1(), "rule__GrupoSeguridad__ZonaDisponibilidadAssignment_4_1");
			builder.put(grammarAccess.getGrupoSeguridadAccess().getDescripcionAssignment_5_1(), "rule__GrupoSeguridad__DescripcionAssignment_5_1");
			builder.put(grammarAccess.getGrupoSeguridadAccess().getReglasSalidaAssignment_8(), "rule__GrupoSeguridad__ReglasSalidaAssignment_8");
			builder.put(grammarAccess.getGrupoSeguridadAccess().getReglasSalidaAssignment_9_1(), "rule__GrupoSeguridad__ReglasSalidaAssignment_9_1");
			builder.put(grammarAccess.getGrupoSeguridadAccess().getReglasEntradaAssignment_13(), "rule__GrupoSeguridad__ReglasEntradaAssignment_13");
			builder.put(grammarAccess.getGrupoSeguridadAccess().getReglasEntradaAssignment_14_1(), "rule__GrupoSeguridad__ReglasEntradaAssignment_14_1");
			builder.put(grammarAccess.getReglaAccess().getTipoAssignment_3_1(), "rule__Regla__TipoAssignment_3_1");
			builder.put(grammarAccess.getReglaAccess().getProtocoloAssignment_4_1(), "rule__Regla__ProtocoloAssignment_4_1");
			builder.put(grammarAccess.getReglaAccess().getPuertoAssignment_5_1(), "rule__Regla__PuertoAssignment_5_1");
			builder.put(grammarAccess.getReglaAccess().getOrigenAssignment_6_1(), "rule__Regla__OrigenAssignment_6_1");
			builder.put(grammarAccess.getReglaAccess().getDescripcionAssignment_7_1(), "rule__Regla__DescripcionAssignment_7_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private CeffectiveGrammarAccess grammarAccess;

	@Override
	protected InternalCeffectiveParser createParser() {
		InternalCeffectiveParser result = new InternalCeffectiveParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public CeffectiveGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CeffectiveGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
