/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.ceffective.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.ceffective.CeffectiveRuntimeModule;
import org.xtext.example.ceffective.CeffectiveStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CeffectiveIdeSetup extends CeffectiveStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CeffectiveRuntimeModule(), new CeffectiveIdeModule()));
	}
	
}
