/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.ceffective.ide;


/**
 * Use this class to register ide components.
 */
public class CeffectiveIdeModule extends AbstractCeffectiveIdeModule {
}
